config/routes.rb
Rails.application.routes.draw do
  resources :evenements
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/evenement.rb
class Evenement < ApplicationRecord
  has_one_attached :photo, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  before_action :set_evenement, only: %i[ show edit update destroy ]

  def index
    @evenements = Evenement.all
  end

  def show
  end


  def new
    @evenement = Evenement.new
  end


  def edit
  end

  def create
    @evenement = Evenement.new(evenement_params)

    respond_to do |format|
      if @evenement.save
        format.html { redirect_to evenement_url(@evenement), notice: "Evenement was successfully created." }
        format.json { render :show, status: :created, location: @evenement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @evenement.update(evenement_params)
        format.html { redirect_to evenement_url(@evenement), notice: "Evenement was successfully updated." }
        format.json { render :show, status: :ok, location: @evenement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @evenement.destroy

    respond_to do |format|
      format.html { redirect_to evenements_url, notice: "Evenement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_evenement
      @evenement = Evenement.find(params[:id])
    end

    def evenement_params
      params.require(:evenement).permit(:title, :date, :participant, :content, :photo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/evenements/_evenement.html.erb
  <p>
    <strong>Titre:</strong>
    <%= evenement.title %>
  </p>

      <p>
        <strong>Date:</strong>
        <%= evenement.date %>
      </p>
      <p>
        <%= image_tag evenement.photo, height: 300, width: 400, crop: :fill %>
      </p>
      <p>
        <strong>Participants:</strong>
        <%= evenement.participant %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= evenement.content %>
      </p>

app/views/evenements/_form.html.erb
<%= simple_form_for(@evenement) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :date %>
    <%= f.input :participant %>
    <%= f.input :content %>
    <%= f.input :photo, as: :file, label: 'Photo' %>
  </div>

  <div class="d-flex justify-content-around">
    <div>
    <%= f.button :submit, class:"btn", value: "Créer événement"%>
    </div>
    <div >
    <%= link_to "Retour événements", evenements_path, class:"btn"%>
    </div>
  </div>
<% end %>

app/views/evenements/edit.html.erb
<h1>Editing evenement</h1>

<%= render "form", evenement: @evenement %>

<br>

<div>
  <%= link_to "Show this evenement", @evenement %> |
  <%= link_to "Back to evenements", evenements_path %>
</div>

app/views/evenements/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Evenements</h1>

<div id="evenements">
  <% @evenements.each do |evenement| %>
    <%= render evenement %>
    <p>
      <%= link_to "Voir cet evenement", evenement %>
    </p>
  <% end %>
</div>

| <%= link_to "Nouvel evenement", new_evenement_path %> |
<%= link_to "Retour acceuil", root_path %> |

app/views/evenements/new.html.erb
<div class="container">
<h1>Ajouter un événement</h1>
  <%= render "form", evenement: @evenement %>


  <div>
    <%# <%= link_to "Retourner aux événements", evenements_path %>
  </div>
</div>

app/views/evenements/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
<h1>Événement crée</h1>
  <%= render @evenement %>

  <div class="d-flex justify-content-around">
    <%= link_to "Editer", edit_evenement_path(@evenement), class:"btn" %>
    <%= link_to "Voir les événements", evenements_path, class:"btn" %>

    <%= button_to "Supprimer événement", @evenement, method: :delete, class:"btn btn-delete" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StartUp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>

    <div class="partners d-flex justify-content-around">
      <%= image_tag"https://res.cloudinary.com/dvinewomn/image/upload/v1679832864/logotalliance_sfmoba.png", height: 150, width: 400, crop: :fill %>
      <%= image_tag"https://res.cloudinary.com/dvinewomn/image/upload/v1679832866/3LogosDso-blac_ry83uw.png", height: 300, width: 300, crop: :fill %>

    </div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
    <div class="f-text"><a class="linkcolor" href="#">À propos</a></div>
    <div class="f-text"><a class="linkcolor" href="#">Nous contacter</a></div>

  <div class="footer-copyright">
    Copyright © 2023 Starts Up, tous droits réservés.
  </div>
    <div class="fa-3x" >
      <%= image_tag"https://res.cloudinary.com/dvinewomn/image/upload/v1679824136/Nice-Starts-Up-LOGO-BLANC_wehd8t.png" %>

    </div>
</div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>Bienvenue Bérengère</h1>
    <div class="container-home mt-5">
      <div class="card">
        <img src="https://i.ibb.co/pWdpN8b/events.jpg" alt="", class="img-home">
        <h3 class='text-center mt-3' >Événements</h3>
        <div class= 'd-flex justify-content-between m-1'>
          <%= link_to "+ Add", new_evenement_path, class:'button' %>
          <%= link_to "View", root_path, class:'btn-detail' %>
        </div>
      </div>
      <div class="card">
        <img src="https://i.ibb.co/hVCjtt8/venir.jpg" alt="", class="img-home">
        <h3 class='text-center mt-3' >Événements à venir</h3>
        <div class= 'd-flex justify-content-between m-1'>
          <%= link_to "+ Add", "#", class:'button' %>
          <%= link_to "View","#", class:'btn-detail' %>
        </div>
      </div>
      <div class="card">
        <img src="https://i.ibb.co/f2RRxKZ/jobs.jpg" alt="", class="img-home">
        <h3 class='text-center mt-3' >Offres d'emploi</h3>
        <div class= 'd-flex justify-content-between m-1'>
          <%= link_to "+ Add", "#", class: 'button' %>
          <%= link_to "View","#", class:'btn-detail' %>
        </div>
      </div>
      <div class="card">
        <img src="https://i.ibb.co/kDrtPtC/community.jpg" alt="", class="img-home">
        <h3 class='text-center mt-3' >Membres contact</h3>
        <div class= 'd-flex justify-content-between m-1'>
          <%= link_to "+ Add", "#", class:'button' %>
          <%= link_to "View","#", class:'btn-detail' %>
        </div>
      </div>
      <div class="card">
        <img src="https://i.ibb.co/FzPZ1RK/cotisation.png" alt="", class="img-home">
        <h3 class='text-center mt-3' >Cotisations</h3>
        <div class= 'd-flex justify-content-between m-1'>
          <%= link_to "+ Add", "#", class:'button' %>
          <%= link_to "View","#", class:'btn-detail' %>
        </div>
      </div>
    </div>
</div>





<%# </div>
</div> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.hml.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
    <div class="f-text"><a class="linkcolor" href="#">À propos</a></div>
    <div class="f-text"><a class="linkcolor" href="#">Nous contacter</a></div>

  <div class="footer-copyright">
    Copyright © 2023 Starts Up, tous droits réservés.
  </div>
    <div class="fa-3x" >
      <img src="/app/assets/images/logo_footer.png/">

    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class ="titre-app">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "image.png" %>
      <% end %>
      <h3 id="main-title">NiceStartsHUB</h3>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dvinewomn/image/upload/v1679833697/avatar_girl_uockpk.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>